#!/usr/bin/env python3
"""Build the pull-request title and body for a milestone from its committed artifacts.

Usage:
    prbody.py --milestone M            print the body (Markdown)
    prbody.py --milestone M --title    print the title only

Every line comes from files in plans/active_milestones/{M}/ and the milestone
branch history, never from chat: intent, group commits, gate verdicts,
declined gates, audit verdicts, the approvals ledger, and the recap link.
"""
import argparse
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import swarmgit as sg  # noqa: E402
import usage  # noqa: E402


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return ""


def section(text, heading):
    m = re.search(rf"^##\s+{re.escape(heading)}\s*\n(.*?)(?=^##\s|\Z)", text, re.M | re.S)
    return m.group(1).strip() if m else ""


def title(root, moniker):
    mdir = sg.milestone_dir(root, moniker)
    for name, pattern in (("spec.md", r"^#\s+Product Specification:\s*(.+)$"), ("intent.md", r"^#\s+(?:Intent:\s*)?(.+)$")):
        m = re.search(pattern, read(os.path.join(mdir, name)), re.M)
        if m:
            return f"feat({moniker}): {m.group(1).strip()}"
    return f"feat({moniker}): {moniker}"


def base_ref(root):
    for ref in ("origin/HEAD", "origin/main", "main", "origin/master", "master"):
        base = sg.git("merge-base", "HEAD", ref, cwd=root)
        if base:
            return base
    return ""


def gate_lines(mdir):
    out = []
    for path in sorted(glob.glob(os.path.join(mdir, "adversarial-reviews", "*.md")) +
                       glob.glob(os.path.join(mdir, "deliberations", "*.md"))):
        text = read(path)
        m = re.search(r"^\|\s*Result\s*\|\s*(.+?)\s*\|\s*$", text, re.M) or \
            re.search(r"^##\s+Verdict\s*\n+(.+)$", text, re.M)
        verdict = m.group(1).strip() if m else "see report"
        out.append(f"- `{os.path.relpath(path, mdir)}`: {verdict}")
    return out


def body(root, moniker):
    mdir = sg.milestone_dir(root, moniker)
    rel = os.path.relpath(mdir, root)
    intent = read(os.path.join(mdir, "intent.md"))
    parts = ["## Intent", f"From `{rel}/intent.md`."]
    for heading in ("Problem", "Outcome"):
        text = section(intent, heading)
        if text:
            parts.append(f"**{heading}.** {' '.join(text.split())}")

    base = base_ref(root)
    log = sg.git("log", "--reverse", "--format=- %h %s", f"{base}..HEAD", cwd=root) if base else ""
    parts += ["", "## What changed", log or "_No commits found against the default branch._"]

    gates = gate_lines(mdir)
    parts += ["", "## Gates", *(gates or ["_No offered gate was run._"])]
    declined = usage.summary(root, moniker)["declined_gates"]
    if declined:
        parts.append("Declined: " + ", ".join(declined) + ".")

    audit = read(os.path.join(mdir, "audit.md"))
    verdicts = re.findall(r"^###\s+(Group .+?)\s*$", audit, re.M)
    parts += ["", "## Audit", *(f"- {v}" for v in verdicts)] if verdicts else ["", "## Audit", "_No audit found._"]

    rows = sg.read_ledger(root, moniker)
    parts += ["", "## Approvals", "| when (UTC) | who | kind | group | tier |", "|---|---|---|---|---|"]
    parts += [f"| {r['when']} | {r['who']} | {r['kind']} | {r['group']} | {r['tier']} |" for r in rows]

    if os.path.exists(os.path.join(mdir, "visual-recap.html")):
        parts += ["", "## Recap", f"`{rel}/visual-recap.html`: open it locally or download it from the CI artifacts."]
    parts += ["", "---", "_Generated by plan-swarm `lib/prbody.py` from committed artifacts._"]
    return "\n".join(parts) + "\n"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--milestone", required=True)
    ap.add_argument("--title", action="store_true")
    a = ap.parse_args(argv)
    if not re.fullmatch(sg.MONIKER, a.milestone):
        print("prbody.py: invalid milestone", file=sys.stderr)
        return 2
    root = sg.repo_root()
    if not os.path.isdir(sg.milestone_dir(root, a.milestone)):
        print(f"prbody.py: no milestone {a.milestone}", file=sys.stderr)
        return 2
    print(title(root, a.milestone) if a.title else body(root, a.milestone), end="\n" if a.title else "")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
