import os
import re
import json
import logging
import asyncio

logger = logging.getLogger("cloud_validator")

class SynthesisFailureException(Exception):
    """Custom exception raised when synthesis fails or cannot return valid JSON."""
    pass

SYNTHESIS_SYSTEM_PROMPT = """You are the Synthesis Model for the cloud-validator review panel.
You are provided with:
1. The target document (spec.md or plan.md)
2. Raw findings from Agent 1 (Spec Skeptic)
3. Raw findings from Agent 2 (Logic Skeptic)

Your job is to:
- Group similar findings by matching their root causes.
- Preserve and utilize the stable kebab-case IDs generated by the source agents for each consolidated finding group. DO NOT generate new IDs.
- Merge the 'failed_attacks' lists from Agent 1 and Agent 2, removing duplicates.
- Act as the third validator: evaluate each consolidated finding and determine whether it represents a genuine issue in the document. Set the 'validated_by_synthesis' field to true if you verify it is a valid issue, or false if you reject it.

Your output MUST be a JSON object with this exact structure:
{
  "consolidated_findings": [
    {
      "id": "stable-kebab-case-id-from-source",
      "clause": "verbatim quote from target document",
      "severity": "high|medium|low",
      "interpretation": "why the clause is problematic",
      "harm": "impact of this issue",
      "tightening": "reworded or new requirements to fix it",
      "sources": ["agent-1", "agent-2"],
      "validated_by_synthesis": true
    }
  ],
  "merged_failed_attacks": [
    "failed-attack-profile-1",
    "failed-attack-profile-2"
  ]
}
"""

SYSTEM_REMINDER = "REMINDER: You must output your response as a single, valid JSON block matching the requested schema inside a ```json ... ``` block. Ensure all fields are present and correct."

def _parse_synthesis_json(text: str) -> dict:
    """Extracts and parses JSON from the synthesis model response."""
    match = re.search(r'```json\s*(.*?)\s*```', text, re.DOTALL | re.IGNORECASE)
    content = None
    if match:
        content = match.group(1).strip()
    else:
        match_outer = re.search(r'\{.*\}', text, re.DOTALL)
        if match_outer:
            content = match_outer.group(0).strip()
            
    if not content:
        raise ValueError("No JSON content found in synthesis reply.")
        
    try:
        data = json.loads(content)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to decode JSON from synthesis reply: {e}") from e
        
    if not isinstance(data, dict) or "consolidated_findings" not in data or "merged_failed_attacks" not in data:
        raise ValueError("Synthesis output missing required top-level 'consolidated_findings' or 'merged_failed_attacks' keys.")
        
    for finding in data["consolidated_findings"]:
        required_keys = ["id", "clause", "severity", "interpretation", "harm", "tightening", "validated_by_synthesis"]
        if not all(k in finding for k in required_keys):
            raise ValueError(f"Consolidated finding is missing one or more required keys: {required_keys}")
            
    return data

async def call_remote_synthesis(project_id: str, location: str, model_name: str, system_prompt: str, user_prompt: str, temperature: float, max_tokens: int) -> str:
    """Invokes remote synthesis model via Vertex AI GenerativeModel SDK."""
    import google.auth
    import vertexai
    from vertexai.generative_models import GenerativeModel
    
    if isinstance(location, str):
        location = location.strip().lower()
    if location not in {"us", "global"}:
        location = "us"
        
    credentials, resolved_project = google.auth.default()
    project = project_id or resolved_project
    
    # Initialize vertexai with project and location
    vertexai.init(project=project, location=location, credentials=credentials)
    
    model = GenerativeModel(
        model_name,
        system_instruction=system_prompt
    )
    
    generation_config = {
        "temperature": temperature,
        "max_output_tokens": max_tokens,
    }
    
    response = await model.generate_content_async(
        user_prompt,
        generation_config=generation_config
    )
    return response.text

def build_synthesis_user_prompt(doc_content: str, agent_1_findings: list, agent_2_findings: list) -> str:
    """Builds the prompt text containing the target document and findings for the synthesis model."""
    user_prompt = f"TARGET DOCUMENT:\n{doc_content}\n\n"
    user_prompt += f"AGENT 1 RAW FINDINGS:\n{json.dumps(agent_1_findings, indent=2)}\n\n"
    user_prompt += f"AGENT 2 RAW FINDINGS:\n{json.dumps(agent_2_findings, indent=2)}\n\n"
    user_prompt += "Please group, consolidate, and validate these findings according to your system instructions."
    return user_prompt

def normalize_clause(clause: str) -> str:
    if not clause:
        return ""
    return re.sub(r'[^a-zA-Z0-9]', '', clause).lower()

def clauses_match(c1: str, c2: str) -> bool:
    nc1 = normalize_clause(c1)
    nc2 = normalize_clause(c2)
    if not nc1 or not nc2:
        return False
    if len(c1) < 15 or len(c2) < 15:
        return nc1 == nc2
    return nc1 == nc2 or nc1 in nc2 or nc2 in nc1

def compute_votes_and_quorum(agent_1_findings: list, agent_2_findings: list, synthesis_output: dict) -> tuple[list, list]:
    """
    Computes votes programmatically in Python using stable ID mapping to prevent hallucinations.
    Classifies findings into confirmed (>= 2 votes) and unconfirmed (1 vote or 0 votes) lists.
    """
    a1_ids = {f["id"] for f in agent_1_findings}
    a2_ids = {f["id"] for f in agent_2_findings}
    
    confirmed = []
    unconfirmed = []
    
    consolidated = synthesis_output.get("consolidated_findings", [])
    
    for finding in consolidated:
        # Build programmatic sources
        sources = []
        if finding.get("id") in a1_ids:
            sources.append("agent-1")
        else:
            # Fallback matching check for Agent 1
            for f1 in agent_1_findings:
                if clauses_match(finding.get("clause", ""), f1.get("clause", "")):
                    sources.append("agent-1")
                    # Preserve original Agent 1 finding ID if we don't have one from a2_ids
                    if finding.get("id") not in a2_ids:
                        finding["id"] = f1.get("id")
                    break
 
        if finding.get("id") in a2_ids:
            sources.append("agent-2")
        else:
            # Fallback matching check for Agent 2
            for f2 in agent_2_findings:
                if clauses_match(finding.get("clause", ""), f2.get("clause", "")):
                    sources.append("agent-2")
                    # Preserve original Agent 2 finding ID if we haven't matched Agent 1
                    if "agent-1" not in sources:
                        finding["id"] = f2.get("id")
                    break
            
        # Programmatic vote count
        votes = len(sources)
        validated_by_synthesis = finding.get("validated_by_synthesis", False)
        if validated_by_synthesis:
            votes += 1
            
        # Update finding fields programmatically
        finding["sources"] = sources
        finding["votes"] = votes
        
        # Quorum classification
        if votes >= 2:
            confirmed.append(finding)
        elif votes == 1 or votes == 0:
            unconfirmed.append(finding)
            
    return confirmed, unconfirmed

async def run_synthesis_with_fallbacks(doc_content: str, agent_1_findings: list, agent_2_findings: list, config: dict) -> dict:
    """Runs the synthesis query with fallbacks, temperature tuning, and reminders on JSON parse failure."""
    synthesis_model = config.get("synthesis_model", "gemini-3-1-flash-lite")
    temperature = config.get("synthesis_temperature", 0.15)
    max_tokens = config.get("synthesis_max_output_tokens", 8192)
    project_id = config.get("gcp_project_id")
    location = config.get("gcp_location", "us")
    if isinstance(location, str):
        location = location.strip().lower()
    if location not in {"us", "global"}:
        location = "us"
    
    system_prompt = SYNTHESIS_SYSTEM_PROMPT
    user_prompt = build_synthesis_user_prompt(doc_content, agent_1_findings, agent_2_findings)
    
    attempts = 3
    last_exception = None
    for attempt in range(1, attempts + 1):
        try:
            logger.info(f"Synthesis call attempt {attempt}/{attempts} (temp={temperature})")
            reply = await call_remote_synthesis(project_id, location, synthesis_model, system_prompt, user_prompt, temperature, max_tokens)
            parsed = _parse_synthesis_json(reply)
            return parsed
        except Exception as e:
            logger.warning(f"Synthesis attempt {attempt} failed: {str(e)}")
            last_exception = e
            # Adjust parameters for retry
            temperature = 0.0
            system_prompt = f"{SYNTHESIS_SYSTEM_PROMPT}\n\n{SYSTEM_REMINDER}"
            if attempt < attempts:
                await asyncio.sleep(2 ** attempt)
            
    raise SynthesisFailureException(f"Synthesis model failed after {attempts} attempts. Last error: {str(last_exception)}") from last_exception
